Update main_app-ocrsolution(argus).yml

diff --git a/.github/workflows/main_app-ocrsolution(argus).yml b/.github/workflows/main_app-ocrsolution(argus).yml
--- a/.github/workflows/main_app-ocrsolution(argus).yml
+++ b/.github/workflows/main_app-ocrsolution(argus).yml
@@ -26,15 +26,20 @@ jobs:
       - name: Install dependencies
         run: pip install -r requirements.txt
 
-      # Package the application files including output.tar.gz
+      # Package the application files
       - name: Package build files
         run: |
           mkdir build
           # Exclude the 'build' directory while copying files
           shopt -s extglob
           cp -r !(build) build/  # Copy everything except 'build' directory
-          # Ensure output.tar.gz is included in the build directory
-          cp output.tar.gz build/
+          # Check if output.tar.gz exists, and then copy it
+          if [ -f output.tar.gz ]; then
+            cp output.tar.gz build/
+          else
+            echo "output.tar.gz not found. Please check your build process."
+            exit 1
+          fi
 
       - name: Upload artifact for deployment jobs
         uses: actions/upload-artifact@v4
